language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec jekyll build
- timeout 120s bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      - secure: Rcp/RIkr1bKnwyUHQxnQ1OUshsIomhm3C4HYSoLlsED/2Fpnskt0kMwdFmowdn0uEWm5zaiIVtRRm7k12GkqkeRvaniQQMt2hoUE4Eog0R56JfurMZ+suDYr8yCg53tQdP8mQ3zR3fmG1xV/Y2i5e3hscD/xfbJIdV0tUnf+bN3XcTryk0WI0twX8Hw6wjxeH2W+39GV8LMqLr/gqMM3IIUG7oqVOgZ0HEGnGNOul6PPhoSF1J0cck0JTrp82HH1KeAp+reHutBYYihxJr+2Z5WGmesRb6v+W/eW40WDDoAbYRhTRVLEMm7rFZf5FGTvLqxTMZX6ezcKhbrAOsV7ICA1W4PjmzdeYShiqGh4Y68kqescXBwL4mW//C+5zZ7Gu9KHsfbNSMWOU+Rg2Ui/MNgbME3X64F7znfHEehQeVoNeFRCIymb/zJF0HBokKSOSzcvLawGD8q1FtCLGCttLG9pA7/1PNn6CHjTNciY5M1gA07/HDgwGlhgUwOMqseM/sREbiblxgYv2CTZwafuzyrVkOcUu1ugD1AWna0P866coF8VO3L+K68nwt5ymOHswnRiyR16B9wE5klGoPJdY5uzb6WID7pN/P9E+V+hAoDmUKQwDAcsmaOzWyijVnfxJPoBTTIEIadAGYLsbEaWuhTxiSkIqJIoaRvU2y836yE=
    on_success: always
